{{- if and .Values.backend.enabled .Values.backend.tempStorage.enabled (not .Values.backend.tempStorage.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "yaytsa.fullname" . }}-backend-temp
  labels:
    {{- include "yaytsa.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.backend.tempStorage.storageClass }}
  storageClassName: {{ .Values.backend.tempStorage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.tempStorage.size }}
{{- end }}
