apiVersion: v1
kind: Service
metadata:
  name: {{ include "yaytsa.fullname" . }}
  labels:
    {{- include "yaytsa.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "yaytsa.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
