apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yaytsa.fullname" . }}
  labels:
    {{- include "yaytsa.labels" . | nindent 4 }}
data:
  JELLYFIN_SERVER_URL: {{ .Values.config.jellyfinServerUrl | quote }}
  JELLYFIN_CLIENT_NAME: {{ .Values.config.clientName | quote }}
  JELLYFIN_DEVICE_NAME: {{ .Values.config.deviceName | quote }}
  APP_VERSION: {{ .Chart.AppVersion | quote }}
